basic.showString("Are you ready?")
music.playMelody("C5 B B C5 A F A F ", 120)
music.playMelody("- E G F D F C E ", 120)
music.playMelody("F G E B A B C5 A ", 120)
music.playMelody("F E G E F E G E ", 120)
music.playMelody("E F E G E A G E ", 120)
music.playMelody("G A E B E A E F ", 120)
music.playMelody("G B C5 G C5 A B C5 ", 120)
music.playMelody("C B C G C E D C ", 120)
